version: '3.8'

services:
    proxy:
        container_name: nginx
        image: nginx:1.25-alpine
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '80:80'
    api:
        container_name: api
        build:
            context: .
            dockerfile: docker/Dockerfile
            target: development
            args:
                - GO_VERSION=1.21-alpine
        volumes:
            - ./api:/srv/api
    database:
      container_name: db
      image: postgres:16-alpine
      restart: always
      environment:
        POSTGRES_PASSWORD: foobar
